```mermaid
mindmap
  root((SQL Database))
    Tables aka The Sheets
      Rows aka Records
      Columns aka Fields
        Data Types
          INTEGER Numbers
          TEXT Strings
          DATE Time
    COMMANDS
      DDL Structure
        CREATE TABLE New Sheet
      DML Data
        INSERT INTO Add Rows
        SELECT Read Rows
          Filters
            WHERE
              = Exact
              <> Not Equal
              > Less/Greater
              IS NULL Void Check
          Math
            + Add
            - Subtract
            || Glue Text
            Functions
              NVL Safety Net
```
